### ISSUE TITLE
"items not orders" and refunds -> maybe we need a shipments table?

### ISSUE THREAD

**Issue by adept** [philipmulcahy/azad#178] opened 2022-01-13 00:04 UTC
I absolutely love new "show items, not orders" checkbox. Unfortunately, it seems that it does not play well with refunds:

- Refunded items are included in the list
- .... with their full price

(this is on amazon.co.uk)

**Comment by philipmulcahy** [comment] 2022-01-21 21:43
Are you able to share an order with an example of this? If so, then please follow https://github.com/philipmulcahy/azad#how-to-save-and-send-an-order-debug-json-file.

**Comment by adept** [comment] 2022-01-23 19:19
Thank for the detailed instructions, debug info sent!

**Comment by Cagey1** [comment] 2023-10-12 22:34
@philipmulcahy I found this thread when I came here to report the same issue. If a run a report **by order**, I get an individual row that basically says "you ordered these five items, for a total of $xx, and then you returned some of it for $yy dollars". But it lumps everything in the order into one row. I prefer the **by item** report, with one row per item. But that report doesn't seem to do anything about returns/refunds, it just shows me every item I ever ordered, one per line. I'd like that item report have an add'l column saying whether I returned that item for refund. So +1 on this as an enhancement request. And I'm happy to do the JSON debug file dance if you need another example for any reason.  (I'm USA Amazon). Thanks, - Ken

**Comment by michaelni** [comment] 2023-12-16 19:49
@philipmulcahy, I also hit this bug :)
Can you explain what the exact problem is ? Why this is difficult ?
i looked at the json file and its a mess but a bit of string searching results in the list of refunded items
example:
Here the first set of product IDs are all the product IDs, the 2nd set Flanked by "Refund" are the returned and refunded 3 items, the next set Flanked by "Refund" and "AmazonUIPageJS" is the set of not returned items (yes i ordered 2 of B07N6V4RTQ and kept one, returned one.
```
egrep -i -o '/product/[^/]*/|refund[ a-zA-Z0-9]*|return complete|AmazonUIPageJS' file.json | uniq -c
      1 /product/B07N6V4RTQ/
      1 /product/B07GGDZTSN/
      1 /product/B0B56T2QKP/
      1 /product/B09Z35S9FS/
      1 /product/B07QV1LC4L/
      1 /product/B00MWQDAZ2/
     27 AmazonUIPageJS
      1 RefundBreakdown
      1 Refund Total
      1 RefundBreakdown
      2 refund
      1 Refund Total
      1 Refund
      1 Return complete
      1 refund has been issued
      1 refund will appear on your bank account or credit card statement within the next 7 days
      1 refunds
      1 refund
      1 Refund subtotal
      2 Refund for this return
      2 /product/B07N6V4RTQ/
      2 /product/B07GGDZTSN/
      2 /product/B0B56T2QKP/
      1 Refund
      1 Refund Status
      2 /product/B09Z35S9FS/
      2 /product/B07N6V4RTQ/
      2 /product/B07QV1LC4L/
      2 /product/B00MWQDAZ2/
     40 AmazonUIPageJS
...
```

**Comment by philipmulcahy** [comment] 2023-12-27 23:12
#194 has morphed into a duplicate of this (to my simple understanding).
@othergun, @fbietlot, @psommerfeld, @richardbowman, @polychromeuganda were the other combatants on 194 - welcome to your new battle arena! (I am feeling newly sympathetic to my product management colleagues at work after spending a couple of hours marshalling github tickets for a couple of hours this evening).

**Comment by philipmulcahy** [comment] 2023-12-30 22:22
I got a usable unit test going using a json file from @adept (thanks), and started to add a refund to the items class, but when I looked a little harder, it appears that the refund belongs to the return shipment: the structure of the html associates the refund amount with the return - e.g. as a sibling of the item list rather than a sibling of the item. Has anyone got an example of more than one item (different items, not just multiple of the same thing) going back in the same shipment? If so, please post here, and send me an order debug json file to azadextension@gmail.com (with #178 somewhere in the subject line).

If we extract the shipment's refund we're going to confuse people because it means it'll be duplicated across the (potentially) multiple returned items in the same return shipment, meaning that folks might wrongly try and sum those duplicate amounts.

Sophisticated users could normalise the shipment info, but there'd be enough who couldn't and would come for me with pitchforks.

In another recent ticket people rejected the need for a shipments table - I'm wondering if we were a bit hasty. I've held off on adding more tables for a long time 'cos it'd involve a fair amount of work and require I introduce radio buttons into the UI (replacing the "items not orders" checkbox).

Can anyone offer suggestions?

(@adept - sorry it's taken so long to move on this!)

**Comment by michaelni** [comment] 2023-12-31 02:03
> I got a usable unit test going using a json file from @adept (thanks), and started to add a refund to the items class, but when I looked a little harder, it appears that the refund belongs to the return shipment: the structure of the html associates the refund amount with the return - e.g. as a sibling of the item list rather than a sibling of the item. Has anyone got an example of more than one item (different items, not just multiple of the same thing) going back in the same shipment? If so, please post here, and send me an order debug json file to [azadextension@gmail.com](mailto:azadextension@gmail.com) (with #178 somewhere in the subject line).

Ive just send you the 2 json files i made 2 weeks ago, hope it helps

**Comment by philipmulcahy** [comment] 2023-12-31 09:52
Awesome @michaelni: I can see at least one of those has a return with more than one item in it, and it's in German which I don't have many examples of in my test pack - thank you!

**Comment by adept** [comment] 2023-12-31 15:27
Sent you an example of two-item return as well.

**Comment by philipmulcahy** [comment] 2023-12-31 17:48
Thanks @adept!
It looks like @michaelni's return shows the refund for the combination of both items, as I feared last night. I'm going to sit on this for a bit, and fix some easier problems. Suggestions are welcome, but right at the moment I feel pulled towards the expensive option - doing the UI upgrade and adding a shipments table.

**Comment by philipmulcahy** [comment] 2023-12-31 18:30
reminder for @philipmulcahy: unit test is based on data/amazon.de/input/028-2936319-1237967_2023-12-16.json

**Comment by philipmulcahy** [comment] 2024-01-03 23:47
As predicted, I found getting the UI working more than a little challenging: https://www.mulcahyfamily.org/azad/azad_189cca59.zip

This version has a lot of changes, so there are very likely to be rough edges.
Here's what I think are the key diffs:
1) checkbox for "show items not orders" is replaced with three radio buttons: orders, items, shipments.
2) the shipments radio button requires subscription to be turned on - I think everyone here is in that state - if you don't it lets you know with an alert box, and kicks you back to orders (items are selectable too, but I had to choose a default).
3) when you click on shipments, it selects the shipments columns checkbox if it's not already checked
4) the shipments table has all of the existing shipments/tracking cols plus ones to tie the rows to the order they belong to
5) new shipment id column (not always available) extracted from the tracking link - not sure if it's useful

Let me know what you think: https://github.com/philipmulcahy/azad/tree/178_shipments_table?tab=readme-ov-file#how-to-try-out-an-experimental-version

**Comment by philipmulcahy** [comment] 2024-01-04 23:04
I think I forgot to include the refunds on the shipments though - I'll get going on this just as soon as I get a chance.

**Comment by philipmulcahy** [comment] 2024-01-06 18:54
https://www.mulcahyfamily.org/azad/azad_4a0f53f2.zip has those refunds.

Folks who are using languages other than english are going to be disappointed - I've been unable to target the refund info sufficiently accurately without resorting to user visible string searches. Although I've now got info on one or two amazon.de orders from kind contributors, they were in english - if you want to send me the same orders in german, I'll happily work through the resulting test failures (I'm guessing there will be quite a few, since why else would our deutsche Freunde be suffering the english version of the .de site?) and add the German amazon strings into the code - it's a fiddly process but pretty much guaranteed to work, to the extent that I'd not need further testing from y'all.

I sense some understandable tester fatigue on this thread. If no-one responds, I'll assume it's all good and get going with merging it into the next production release.
Yours,

Philip

**Closed** 2024-01-06 19:26 UTC
Labels: enhancement, fixed_in_master, difficult
