### ISSUE TITLE
Can't Download CSV

### ISSUE THREAD

**Issue by JustinPFryer** [philipmulcahy/azad#110] opened 2020-07-08 10:52 UTC
Everything runs fine, I've cleared cache, cleared google history and cache, the data for orders appears (1700+) and all completes however I click downloads CSV and nothing happens, doesn't matter how long I wait, if I try and click again, if I use on different computer etc

**Comment by JustinPFryer** [comment] 2020-07-08 16:06
Oh and a superb extension normally =o) thanks very much...

**Comment by amitsagar4** [comment] 2020-07-09 05:05
Make that two of us. Having the same issue.

**Comment by JustinPFryer** [comment] 2020-07-09 16:36
Odd, do you have a lot of orders too?

**Comment by amitsagar4** [comment] 2020-07-09 17:39
yes

**Comment by philipmulcahy** [comment] 2020-07-10 22:57
1) When you press the csv button, what stats does the popup control show? For example mine currently shows "queued:0; running:0; completed:172; errors:0; cache_hits:0"
2) Would you mind attaching a console log from after you've pressed the csv button?
Thanks,
Philip

**Comment by JustinPFryer** [comment] 2020-07-11 11:44
It all finishes perfectly.. 1750 orders , 0 errors, etc etc the plain table complete with all details, exactly as it used to. However I click the download spreadsheet and nothing happens.

Just checked the console log and I am getting this

amazon_order_history_table.displayOrders starting
table.ts:456 amazon_order_history_table.displayOrders then func starting
table.ts:338 amazon_order_history_table.reallyDisplayOrders starting
table.ts:280 adding table
table.ts:282 added table
table.ts:427 azad.reallyDisplayOrders returning
table.ts:460 amazon_order_history_table.displayOrders then func returning
order-history?ref_=nav_orders_first:1 Error handling response: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at chrome-extension://mgkilgclilajckgnedgjgnfdokkgnibi/inject.bundle.js:266127:35

Thanks for your help

**Comment by philipmulcahy** [comment] 2020-07-11 21:05
Hi  Justin,

Can you paste in the complete status message please?
(Just because you can't see any activity doesn't mean that it thinks it has finished.)
Also, can you give me the whole log, as an uploaded file rather than just that snippet?

Thanks,

Philip

**Comment by JustinPFryer** [comment] 2020-07-11 22:11
[consolelog.log](https://github.com/philipmulcahy/azad/files/4907671/consolelog.log)

queued:0; running:0; completed:1805; errors:0; cache_hits:1804 

Thanks

**Comment by mberth** [comment] 2020-07-12 09:38
Same problem here, 
[www.amazon.de-1594546542265.log](https://github.com/philipmulcahy/azad/files/4908269/www.amazon.de-1594546542265.log)

**Comment by neilyoung** [comment] 2020-07-12 10:12
Same problem here for 2019, 75 orders

![image](https://user-images.githubusercontent.com/731020/87243775-ebb5e300-c438-11ea-9206-e4739e87ea6d.png)

**Comment by philipmulcahy** [comment] 2020-07-12 21:20
Thanks for the logs. It's not completely obvious what's up - most likely JSON.parse is blowing up on some bad input, but I'm not completely sure where in the code this is happening (there are several candidate locations).

1) I have added some better logging code around all of the candidates and included in 1.9.9 which is in review with Google now (they have become very strict with extensions that can inject content scripts recently). If all goes well it'll be released/deployed tomorrow.

2) Have any of you tried removing amazon cookies (see https://github.com/philipmulcahy/azad/blob/master/README.md) and also removing and reinstalling the extension? I'm wondering if it could be something to do with the extension's settings or cache. Removing the cookies and reinstalling the extension would delete all of that state.

**Comment by JustinPFryer** [comment] 2020-07-12 21:31
Hi,

I have tried removing and re-adding to no avail, i clear Google cache as
had issues with the previous version as well if i didn't do so, however
wasn't a large issue.

Will remove and re-add when the new version available and let you know how
i get on.

Thank you,

Justin

**Comment by JustinPFryer** [comment] 2020-07-13 07:14
Hi,

So I removed and then added the new version and am not even seeing an 
output now?

thanks,

Justin

**Comment by JustinPFryer** [comment] 2020-07-13 09:29
I just get a blank screen, everything finishes okay with all orders processed and no errors 

queued:0; running:0; completed:1826; errors:0; cache_hits:1825

But no details displayed, just a blank page. (This after installing latest version)

**Comment by neilyoung** [comment] 2020-07-13 09:52
Can confirm that. Network requests running and make sense on examination. Final page in the browser completely empty.
Developer console full of 

`Finished https://www.amazon.de/gp/your-account/order-details/ref=oh_aui_or_o01_?ie=UTF8&orderID=XXXXXX with queue size 0
`
(anonymized), no obvious error.

But really nothing in the view, even in the developer console. 

I have not actively updated the plugin, but I remember, it worked at least and I saw my purchases yesterday or the day before.

**Comment by neilyoung** [comment] 2020-07-13 09:55
Wait. After hovering over the top left corner at least somewhat like a menu appears. But nothing happens on `Close menu` and there is also no way to make the purchases visible.

**Comment by philipmulcahy** [comment] 2020-07-13 09:56
I am a bad man. I haven’t worked out what happened.
Please see my post from a couple of minutes ago with a static version of 1.9.10 (aka 1.9.8) that may be useful to you until I manage to fix and push a version that works.

**Comment by neilyoung** [comment] 2020-07-13 09:59
Hmm. What post are you referring to? Link?

**Comment by JustinPFryer** [comment] 2020-07-13 09:59
Not a bad man lol. . very useful little extension when it works and much appreciated

**Comment by neilyoung** [comment] 2020-07-13 09:59
Yepp. Second that.

**Comment by philipmulcahy** [comment] 2020-07-13 10:00
Github won’t let me mail them the built zip file for 1.9.10 - I will post it shortly for download on my home website provide the url here.

**Comment by neilyoung** [comment] 2020-07-13 10:01
OK, don't worry. Take your time. Nothing is burning :)

**Comment by philipmulcahy** [comment] 2020-07-13 10:20
Here’s how to use a static copy - (disconnected from the chrome web store)

1) download: https://www.mulcahyfamily.org/azad/azad_1_9_10.zip <https://www.mulcahyfamily.org/azad/azad_1_9_10.zip>
2) unzip it - you should get a folder called “build”
3) open chrome://extensions <chrome://extensions>
4) disable the web store copy by clicking on the slider for order history reporter
5) click on “Load unpacked” and choose the unzipped “build” folder
6) refresh any amazon pages you have open
7) you might need to click on the jigsaw icon on the address bar (right hand side) to find the extension button

**Comment by neilyoung** [comment] 2020-07-13 10:38
OK, this one works and the developer console logs this:

```
amazon_order_history_table.displayOrders then func returning
yourstore?ie=UTF8&ref=ox_checkout_redirects_yourstore:3034 Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): {"m":"Event execution failed for event resizeCannot read property 'top' of null","name":"TypeError","csm":"v6 ueLogError stack","logLevel":"FATAL","attribution":"RecommendationsYourStoreAssets:card-scrolling-listener","pageURL":"https://www.amazon.de/gp/yourstore?ie=UTF8&ref=ox_checkout_redirects_yourstore","f":"https://images-eu.ssl-images-amazon.com/images/I/01L1n-x1BaL._RC%7C01WXE-qjS2L.js,31N-2Rn7AiL.js,11l699oGQML.js,41uqrok1ruL.js_.js?AUIClients/RecommendationsYourStoreHomeMetaAsset_v2","l":"53","s":["TypeError: Cannot read property 'top' of null","at getGridStart (https://images-eu.ssl-images-amazon.com/images/I/01L1n-x1BaL._RC%7C01WXE-qjS2L.js,31N-2Rn7AiL.js,11l699oGQML.js,41uqrok1ruL.js_.js?AUIClients/RecommendationsYourStoreHomeMetaAsset_v2:53:288)","at getGridSecondLastRowStart (https://images-eu.ssl-images-amazon.com/images/I/01L1n-x1BaL._RC%7C01WXE-qjS2L.js,31N-2Rn7AiL.js,11l699oGQML.js,41uqrok1ruL.js_.js?AUIClients/RecommendationsYourStoreHomeMetaAsset_v2:54:17)","at g.onScroll (https://images-eu.ssl-images-amazon.com/images/I/01L1n-x1BaL._RC%7C01WXE-qjS2L.js,31N-2Rn7AiL.js,11l699oGQML.js,41uqrok1ruL.js_.js?AUIClients/RecommendationsYourStoreHomeMetaAsset_v2:54:195)","at https://images-eu.ssl-images-amazon.com/images/I/01L1n-x1BaL._RC%7C01WXE-qjS2L.js,31N-2Rn7AiL.js,11l699oGQML.js,41uqrok1ruL.js_.js?AUIClients/RecommendationsYourStoreHomeMetaAsset_v2:63:189","at https://www.amazon.de/gp/yourstore?ie=UTF8&ref=ox_checkout_redirects_yourstore:110:391","at f (https://images-eu.ssl-images-amazon.com/images/I/61-6nKPKyWL._RC%7C11Y+5x+kkTL.js,61Usf6ZKPoL.js,212PEt8u8bL.js,012FVc3131L.js,11KoZmq92cL.js,51TNaPzHULL.js,11AHlQhPRjL.js,01-Ag-OPDsL.js,11SvFon9IkL.js,11p81T3qWFL.js,21ssiLNIZvL.js,0190vxtlzcL.js,61N4mcEKRxL.js,01ezj5Rkz1L.js,11EemQQsS-L.js,31pOTH2ZMRL.js,01rpauTep4L.js,01iyxuSGj4L.js,01CRyJpOGrL.js_.js?AUIClients/AmazonUI:247:43)","at https://images-eu.ssl-images-amazon.com/images/I/61-6nKPKyWL._RC%7C11Y+5x+kkTL.js,61Usf6ZKPoL.js,212PEt8u8bL.js,012FVc3131L.js,11KoZmq92cL.js,51TNaPzHULL.js,11AHlQhPRjL.js,01-Ag-OPDsL.js,11SvFon9IkL.js,11p81T3qWFL.js,21ssiLNIZvL.js,0190vxtlzcL.js,61N4mcEKRxL.js,01ezj5Rkz1L.js,11EemQQsS-L.js,31pOTH2ZMRL.js,01rpauTep4L.js,01iyxuSGj4L.js,01CRyJpOGrL.js_.js?AUIClients/AmazonUI:249:443","at k (https://images-eu.ssl-images-amazon.com/images/I/61-6nKPKyWL._RC%7C11Y+5x+kkTL.js,61Usf6ZKPoL.js,212PEt8u8bL.js,012FVc3131L.js,11KoZmq92cL.js,51TNaPzHULL.js,11AHlQhPRjL.js,01-Ag-OPDsL.js,11SvFon9IkL.js,11p81T3qWFL.js,21ssiLNIZvL.js,0190vxtlzcL.js,61N4mcEKRxL.js,01ezj5Rkz1L.js,11EemQQsS-L.js,31pOTH2ZMRL.js,01rpauTep4L.js,01iyxuSGj4L.js,01CRyJpOGrL.js_.js?AUIClients/AmazonUI:247:380)","at Object.trigger (https://images-eu.ssl-images-amazon.com/images/I/61-6nKPKyWL._RC%7C11Y+5x+kkTL.js,61Usf6ZKPoL.js,212PEt8u8bL.js,012FVc3131L.js,11KoZmq92cL.js,51TNaPzHULL.js,11AHlQhPRjL.js,01-Ag-OPDsL.js,11SvFon9IkL.js,11p81T3qWFL.js,21ssiLNIZvL.js,0190vxtlzcL.js,61N4mcEKRxL.js,01ezj5Rkz1L.js,11EemQQsS-L.js,31pOTH2ZMRL.js,01rpauTep4L.js,01iyxuSGj4L.js,01CRyJpOGrL.js_.js?AUIClients/AmazonUI:251:258)","at https://images-eu.ssl-images-amazon.com/images/I/61-6nKPKyWL._RC%7C11Y+5x+kkTL.js,61Usf6ZKPoL.js,212PEt8u8bL.js,012FVc3131L.js,11KoZmq92cL.js,51TNaPzHULL.js,11AHlQhPRjL.js,01-Ag-OPDsL.js,11SvFon9IkL.js,11p81T3qWFL.js,21ssiLNIZvL.js,0190vxtlzcL.js,61N4mcEKRxL.js,01ezj5Rkz1L.js,11EemQQsS-L.js,31pOTH2ZMRL.js,01rpauTep4L.js,01iyxuSGj4L.js,01CRyJpOGrL.js_.js?AUIClients/AmazonUI:305:276"],"t":33111,"fcsmln":2,"cinfo":{"1":"<head><script async=\"\" src=\"https://images-na.ssl-images-amazon.com/images/I/71gyQFFZWjL.js\" crossorigin=\"anonymous\"></script><script async=\"\" src=\"https://images-na.ssl-images-amazon.com/images/I/31O-NHNOeqL.js\" crossorigin=\"anonymous\"></script>"}} Object
z @ yourstore?ie=UTF8&ref=ox_checkout_redirects_yourstore:3034
```

**Comment by neilyoung** [comment] 2020-07-13 10:47
But this is not the problem for the CSV download: The attempt to download CSV brings this:

```
amazon_order_history_table.displayOrders then func returning
yourstore?ie=UTF8&ref=ox_checkout_redirects_yourstore:1 Error handling response: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at chrome-extension://kekjikhejcjpihkcgcnijnkjbihhfdmd/inject.bundle.js:266272:35
```

Following the code, there is obviously a boolean expected, which is not there.

```
export function getBoolean(key: string): Promise<boolean> {
    return new Promise<boolean>( function( resolve ) {
        chrome.storage.sync.get(
            KEY,
            function(entries) {
                const settings = JSON.parse(entries[KEY]);
                const key_to_elem: Record<string, HTMLElement> = {};
                const value: boolean = <boolean>settings[key];
                resolve(value);
            }
        );
    });
}
```

Set. a breakpoint there, the `entries` object is empty, key is `azad_settings` or so.

**Comment by philipmulcahy** [comment] 2020-07-13 10:52
Thanks Neil! Selective log pastes on their own are not that useful unless we’re both talking about a very specific bit of code - it’s much easier to search an entire log (and not have as much round tripping between us). I’ve managed to reproduce the blank screen issue on another computer here btw, so have a rest and get ready to send me logs once I get the blank screen fixed - I want to sort the csv thing, which is going to be trickier and require your help.

Yours,

Philip

**Comment by neilyoung** [comment] 2020-07-13 10:54
Sure.

**Comment by philipmulcahy** [comment] 2020-07-13 10:58
This is one of the locations I instrumented last night (that you’re gonna have to wait for!)
It seems super plausible as the cause.
In the mean time (before 1.9.9 disappears), can you try clicking on the two settings checkboxes to see if that helps (before pressing a year button)? I’m wondering if never having made the settings causes the problem. (e.g. I need to have a default in the code)

**Comment by JustinPFryer** [comment] 2020-07-13 11:00
Yes thank you, back now to visible orders but no CSV download as you 
expected.

**Comment by neilyoung** [comment] 2020-07-13 11:06
Clicking around on the two checkboxes just brings new problems in developer console. "JSON parser blew up" and "Cannot read show_invoice_links of null"

**Comment by philipmulcahy** [comment] 2020-07-14 20:43
I think this build fixes the blank screen issue: [azad_4dc7500c.zip](https://www.mulcahyfamily.org/azad/azad_4dc7500c.zip)
As someone suspected, it was caused by poor corner case handling in settings retrieval.

1) Would you mind checking it before I submit it to the web store? See [above post](https://github.com/philipmulcahy/azad/issues/110#issuecomment-657472022) on how to use it.
2) If you can get the csv problem to recur, so much the better, and if so, please attach your log file.

Thanks!

**Comment by neilyoung** [comment] 2020-07-14 20:54
Works like a charm. Still a lot of errors in the dev console, but works for me

**Comment by philipmulcahy** [comment] 2020-07-14 21:00
That's amazingly speedy! Can you send the log and I'll look at the errors - be aware that some of them might be from non-azad code - On my browser I see some moaning from an ad blocking extension that is fighting with amazon code, and some directly from amazon's code.

**Comment by philipmulcahy** [comment] 2020-07-14 21:01
@neilyoung just to confirm: are you saying the csv thing is working for you?

**Comment by neilyoung** [comment] 2020-07-14 21:02
```
azad.reallyDisplayOrders returning
chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266771 amazon_order_history_table.displayOrders then func returning table promise.
77chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266335 JSON.parse blew up with: SyntaxError: Unexpected token u in JSON at position 0 while parsing:undefined
(anonymous) @ chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266335
chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266767 amazon_order_history_table.displayOrders starting
chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266769 amazon_order_history_table.displayOrders then func starting
chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266682 amazon_order_history_table.reallyDisplayOrders starting
chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266641 adding table
chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266643 added table
chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266754 azad.reallyDisplayOrders returning
chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266771 amazon_order_history_table.displayOrders then func returning table promise.
677chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266335 JSON.parse blew up with: SyntaxError: Unexpected token u in JSON at position 0 while parsing:undefined
(anonymous) @ chrome-extension://popffomacomnnogadlobfkmelfjdpapp/inject.bundle.js:266335
yourstore:3056 Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): {"m":"Event execution failed for event resizeCannot read property 'top' of null","name":"TypeError","csm":"v6 ueLogError stack","logLevel":"FATAL","attribution":"RecommendationsYourStoreAssets:card-scrolling-listener","pageURL":"https://www.amazon.de/gp/yourstore?ie=UTF8&ref=ox_checkout_redirects_yourstore","f":"https://images-eu.ssl-images-amazon.com/images/I/01L1n-x1BaL._RC%7C01WXE-qjS2L.js,31N-2Rn7AiL.js,11l699oGQML.js,41uqrok1ruL.js_.js?AUIClients/RecommendationsYourStoreHomeMetaAsset_v2","l":"53","s":["TypeError: Cannot read property 'top' of null","at getGridStart (https://images-eu.ssl-images-amazon.com/images/I/01L1n-x1BaL._RC%7C01WXE-qjS2L.js,31N-2Rn7AiL.js,11l699oGQML.js,41uqrok1ruL.js_.js?AUIClients/RecommendationsYourStoreHomeMetaAsset_v2:53:288)","at getGridSecondLastRowStart (https://images-eu.ssl-images-amazon.com/images/I/01L1n-x1BaL._RC%7C01WXE-qjS2L.js,31N-2Rn7AiL.js,11l699oGQML.js,41uqrok1ruL.js_.js?AUIClients/RecommendationsYourStoreHomeMetaAsset_v2:54:17)","at g.onScroll (https://images-eu.ssl-images-amazon.com/images/I/01L1n-x1BaL._RC%7C01WXE-qjS2L.js,31N-2Rn7AiL.js,11l699oGQML.js,41uqrok1ruL.js_.js?AUIClients/RecommendationsYourStoreHomeMetaAsset_v2:54:195)","at https://images-eu.ssl-images-amazon.com/images/I/01L1n-x1BaL._RC%7C01WXE-qjS2L.js,31N-2Rn7AiL.js,11l699oGQML.js,41uqrok1ruL.js_.js?AUIClients/RecommendationsYourStoreHomeMetaAsset_v2:63:189","at https://www.amazon.de/gp/yourstore?ie=UTF8&ref=ox_checkout_redirects_yourstore:110:391","at f (https://images-eu.ssl-images-amazon.com/images/I/61-6nKPKyWL._RC%7C11Y+5x+kkTL.js,61Usf6ZKPoL.js,212PEt8u8bL.js,012FVc3131L.js,11KoZmq92cL.js,51TNaPzHULL.js,11AHlQhPRjL.js,01-Ag-OPDsL.js,11SvFon9IkL.js,11p81T3qWFL.js,21ssiLNIZvL.js,0190vxtlzcL.js,61N4mcEKRxL.js,01ezj5Rkz1L.js,11EemQQsS-L.js,31pOTH2ZMRL.js,01rpauTep4L.js,01iyxuSGj4L.js,01CRyJpOGrL.js_.js?AUIClients/AmazonUI:247:43)","at https://images-eu.ssl-images-amazon.com/images/I/61-6nKPKyWL._RC%7C11Y+5x+kkTL.js,61Usf6ZKPoL.js,212PEt8u8bL.js,012FVc3131L.js,11KoZmq92cL.js,51TNaPzHULL.js,11AHlQhPRjL.js,01-Ag-OPDsL.js,11SvFon9IkL.js,11p81T3qWFL.js,21ssiLNIZvL.js,0190vxtlzcL.js,61N4mcEKRxL.js,01ezj5Rkz1L.js,11EemQQsS-L.js,31pOTH2ZMRL.js,01rpauTep4L.js,01iyxuSGj4L.js,01CRyJpOGrL.js_.js?AUIClients/AmazonUI:249:443","at k (https://images-eu.ssl-images-amazon.com/images/I/61-6nKPKyWL._RC%7C11Y+5x+kkTL.js,61Usf6ZKPoL.js,212PEt8u8bL.js,012FVc3131L.js,11KoZmq92cL.js,51TNaPzHULL.js,11AHlQhPRjL.js,01-Ag-OPDsL.js,11SvFon9IkL.js,11p81T3qWFL.js,21ssiLNIZvL.js,0190vxtlzcL.js,61N4mcEKRxL.js,01ezj5Rkz1L.js,11EemQQsS-L.js,31pOTH2ZMRL.js,01rpauTep4L.js,01iyxuSGj4L.js,01CRyJpOGrL.js_.js?AUIClients/AmazonUI:247:380)","at Object.trigger (https://images-eu.ssl-images-amazon.com/images/I/61-6nKPKyWL._RC%7C11Y+5x+kkTL.js,61Usf6ZKPoL.js,212PEt8u8bL.js,012FVc3131L.js,11KoZmq92cL.js,51TNaPzHULL.js,11AHlQhPRjL.js,01-Ag-OPDsL.js,11SvFon9IkL.js,11p81T3qWFL.js,21ssiLNIZvL.js,0190vxtlzcL.js,61N4mcEKRxL.js,01ezj5Rkz1L.js,11EemQQsS-L.js,31pOTH2ZMRL.js,01rpauTep4L.js,01iyxuSGj4L.js,01CRyJpOGrL.js_.js?AUIClients/AmazonUI:251:258)","at https://images-eu.ssl-images-amazon.com/images/I/61-6nKPKyWL._RC%7C11Y+5x+kkTL.js,61Usf6ZKPoL.js,212PEt8u8bL.js,012FVc3131L.js,11KoZmq92cL.js,51TNaPzHULL.js,11AHlQhPRjL.js,01-Ag-OPDsL.js,11SvFon9IkL.js,11p81T3qWFL.js,21ssiLNIZvL.js,0190vxtlzcL.js,61N4mcEKRxL.js,01ezj5Rkz1L.js,11EemQQsS-L.js,31pOTH2ZMRL.js,01rpauTep4L.js,01iyxuSGj4L.js,01CRyJpOGrL.js_.js?AUIClients/AmazonUI:305:276"],"t":65603,"fcsmln":2,"cinfo":{"1":"<head><script async=\"\" src=\"https://images-na.ssl-images-amazon.com/images/I/71gyQFFZWjL.js\" crossorigin=\"anonymous\"></script><script async=\"\" src=\"https://images-na.ssl-images-amazon.com/images/I/31O-NHNOeqL.js\" crossorigin=\"anonymous\"></script>"}} Object
z @ yourstore:3056
```

**Comment by neilyoung** [comment] 2020-07-14 21:03
CSV is working

**Comment by JustinPFryer** [comment] 2020-07-14 21:11
Works for me too thanks on CSV downloads, although card payment says pending and then card details for every line? =o)

**Comment by philipmulcahy** [comment] 2020-07-14 21:43
Well spotted! This is happening after the code that is unit tested, and so relies (for the moment) on eyeballs to inspect.

I think that should be easy to fix - is it OK if I send you another test build tonight/tomorrow?

**Comment by JustinPFryer** [comment] 2020-07-14 21:45
Of course.. Going to have an early night tonight so okay if i run a test
tomorrow

**Comment by philipmulcahy** [comment] 2020-07-14 22:03
I am done for the night - good luck tomorrow: [azad_c96df978.zip](https://www.mulcahyfamily.org/azad/azad_c96df978.zip)

**Comment by mrbeegit** [comment] 2020-07-15 10:40
I have the same issue, just nothing happening when clicking download.csv button. I have downloaded that azad zip file, extracted the build folder, turned off the extension in chrome (also tried this in the new edge browser). 
I get to this step "5) click on “Load unpacked” and choose the unzipped “build” folder "

..but I am not sure where load unpacked is, i cant find it in the build folder or anywhere (am stupid!). All that is in the build folder is a file i can use which is popup.html but this opens the popup window where i can only select two years, 2027 and 2097 lol so I am totally off track here.

I have cleared cache, tried it also in edge browser, but it just doesnt download the csv file, it sort of hangs there as if itll download because the hand pointer is on the screen and when you move it around it doesnt change and you cant click on any links or orders in the table, so it is loading something but nothing downloads!

**Comment by philipmulcahy** [comment] 2020-07-15 11:44
Hi. I am away from computer now, but suspect I missed a step for switching to the test version... you need to enable developer mode in Chrome. Not sure if that is a slider in chrome://extensions or somewhere else. That will make “load unpacked” visible.
Very interested in seeing an entire log for a csv failure from the test version...
Remember to make sure the store version is disabled: having two azads fighting each other is messy.

**Comment by mrbeegit** [comment] 2020-07-15 12:18
Thanks for the fast reply!
I selected developer mode and i saw the option to load unpacked as you advised and it worked perfectly! Loaded them all up, and clicked download csv and it downloaded and its all there. So strange!

**Comment by philipmulcahy** [comment] 2020-07-15 19:35
OK - I think I know what's been happening... both problems (csv and blank table) were caused by me making changes to how settings are retrieved from the chrome storage api, and not thinking to test a clean install (that didn't have any azad settings).
I will push the test version out to the store tonight - thank you everyone. Don't forget to disable the local version when the new one is out: v1.9.11 ?
Yours,
Philip

**Comment by philipmulcahy** [comment] 2020-07-15 20:35
1.9.11 it is (if/when the reviewbot lets it into the store).

**Comment by neilyoung** [comment] 2020-07-16 10:02
Seems to work fine, although the developer console is full of red lines :)

One thing: In table as well as CSV there is a ";" at the end of each line. Maybe this can be stripped. But this is not even an annoyance. :)

Great job. Thanks for fixing it that fast

**Comment by philipmulcahy** [comment] 2020-07-16 19:25
I know how to get rid of the red lines that I'm causing - I'll get to it one day.
Closing this ticket now - thank you everyone for helping!

**Closed by philipmulcahy** 2020-07-16 19:25 UTC

**Comment by JustinPFryer** [comment] 2020-07-16 20:49
Thank you!!!
