### ISSUE TITLE
Missing lots of rows 

### ISSUE THREAD

**Issue by mimiGT772** [philipmulcahy/azad#293] opened 2024-09-28 15:02 UTC
Tried the extension to get my 2023 order history. Selected to see items in the extension. Ran it several times, had to keep trying because Amazon logged me out a couple of times in the process (WTH) but when I finally got the export, it only had 57 items but Amazon says I placed 227 orders in 2023. Doesn't seem to be working properly and maybe there is nothing you can do to help as it may be Amazon blocking the extract (not sure why - what a bunch of crap!) but in case there is a way to improve I wanted to report this. Thank you for creating this extension, just wish it would work for me.

**Comment by philipmulcahy** [comment] 2024-09-29 06:13
Sorry you are having such a frustrating time. Can you please share a console log for such a failed run?If you get the logged out warning, remember that you should NOT clear the cache, so that subsequent attempts can build on the progress made previously instead of starting from nothing: cached pages are pages that don’t need to be fetched from Amazon again.Sent from my phoneOn 28 Sep 2024, at 16:02, mimiGT772 ***@***.***> wrote:﻿
Tried the extension to get my 2023 order history. Selected to see items in the extension. Ran it several times, had to keep trying because Amazon logged me out a couple of times in the process (WTH) but when I finally got the export, it only had 57 items but Amazon says I placed 227 orders in 2023. Doesn't seem to be working properly and maybe there is nothing you can do to help as it may be Amazon blocking the extract (not sure why - what a bunch of crap!) but in case there is a way to improve I wanted to report this. Thank you for creating this extension, just wish it would work for me.

**Comment by kms54321** [comment] 2024-10-01 18:14
I am having this problem as well, the extension worked perfectly for me two weeks ago, but when I tried it today - attempting to download ITEMS from the last month, 3 months, and year - in each case Amazon popped open a "sorry we couldn't find that page" tab. The scraped list then has gaps, with missing items spread throughout the table.

If I run the extension for ORDERS, I get a list showing all of my orders, but many of them show nothing in the <items> column, and several show only "ending in : ;" in the <payments> column.

I've tried it ensuring that one a single Amazon tab is open, while being certain to have both cleared the extension's cache and purged my browsers cache and local storage for amazon.com. as well as running it successively without clearing the extension cache or my browser cache. I end up with missing items no matter what.

This extension has been very helpful to me, I thank you for creating it, and I have donated. I do not know how to get a "console log," but if I can figure that out then I will either post it or send it to you as appropriate.

Thanks!

**Comment by philipmulcahy** [comment] 2024-10-01 19:46
I think I just managed to reproduce this on my account today - it looks like maybe Amazon are rolling out a change of some sort - I'll get to work on understanding what that change is and how azad can cope with it.

**Comment by philipmulcahy** [comment] 2024-10-01 20:13
I have constructed a failing unit test using captured debug data from a recent physical order of mine for a single item.

(translation: I've got something reproducible that I can point a debugger at and understand what's going on without annoying Amazon with repeated calls to the same urls)

**Comment by philipmulcahy** [comment] 2024-10-02 08:56
Amazon appear have a new html "schema" for item/sku data on order detail pages, and they're using it heavily.

The code I've added to this dev build https://mulcahyfamily.org/azad/azad_72fe13cb.zip seems to fix the majority of problems, but I'm still seeing some digital order problems (though they may not be new).
Additionally, I get exactly one bad URL reported during a 2024 run on my account: https://www.amazon.co.uk/dp/B07VVS4WLS/ref=docs-os-doi_0

Please test [azad_72fe13cb.zip](https://mulcahyfamily.org/azad/azad_72fe13cb.zip) and give me feedback, particularly if you're an amazon.com user (e.g. USA based). [Here's how to install and use a dev build.](https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-try-out-an-experimental-version)

Yours,

Philip

**Comment by philipmulcahy** [comment] 2024-10-02 10:18
At least some of the 404s are Amazon's fault. They're coming from some digital orders, where links that Amazon has on the order page (that should point to the SKU/title page) are dead - for example...
<img width="1496" alt="Screenshot 2024-10-02 at 11 13 36" src="https://github.com/user-attachments/assets/f864415f-3a45-4a57-b8b4-700c07a991fa">
the circled title link is https://www.amazon.co.uk/dp/B00H3781DG/ref=docs-os-doi_0
which 404s: 
<img width="1123" alt="image" src="https://github.com/user-attachments/assets/47ef23da-e5db-434a-acd8-5f36216a61d4">

**Comment by philipmulcahy** [comment] 2024-10-02 10:42
The remaining "funny" digital orders (that show as "pending" in the date field and blank in all other columns except for order id) are all month long digital subscriptions to Disney or Paramount (thanks kids!). The Paramount order pages are spectacularly uninformative: 
<img width="1494" alt="image" src="https://github.com/user-attachments/assets/018a5aae-2f56-4d79-af08-035b396d8de7">
<img width="1475" alt="Screenshot 2024-10-02 at 11 41 46" src="https://github.com/user-attachments/assets/f6cc563b-8307-4bfb-b3be-b1af915f3b79">

**Comment by philipmulcahy** [comment] 2024-10-02 11:27
I have one outstanding concern - the new code I've written does not handle item quantities for non-single quantities. Has anyone got a misbehaving recent order where they've bought more than one of a thing in the same order. If you have, please share the order debug json file (see readme for instructions on how to capture and share safely).
Thank you!

**Comment by philipmulcahy** [comment] 2024-10-02 14:54
Quantity is sorted now, and I'm going after shipment info next - expect a new dev build in a few hours for UAT.

**Comment by kms54321** [comment] 2024-10-02 15:02
Wow! Thank you for being so responsive!

**Comment by philipmulcahy** [comment] 2024-10-02 15:55
this is turning out to be quite fiddly, but I'm making good progress: https://github.com/philipmulcahy/azad/compare/master...293_new_item_schema

**Comment by philipmulcahy** [comment] 2024-10-02 16:40
Shipments - the youngest multi-shipment order I have in my account (early September) appears to be the "old" kind, and is being scraped correctly with the old code, but newer single shipment orders are broken in regards to shipments.

**Comment by philipmulcahy** [comment] 2024-10-02 21:27
I'm still hacking away at shipments.

**Comment by philipmulcahy** [comment] 2024-10-02 21:56
yay!

**Comment by philipmulcahy** [comment] 2024-10-02 22:20
The transaction column is empty for all of my 2023 and 2024 orders. I think that this behaviour change is across all orders, not just new ones. I'm not going to hold up pushing a release to fix the rest of the new problems, but I do want to get somewhere with restoring basic shipment info ASAP, hence creating separate #295

**Comment by philipmulcahy** [comment] 2024-10-03 06:50
@kms54321 I forgot to mention that I have fixed the double price thing in my branch. I can now see a way through to getting shipments working (though not transactions), I just need to put the time in. I think there is a reasonable prospect of a test/UAT build on Friday.Sent from my phoneOn 2 Oct 2024, at 22:43, kms54321 ***@***.***> wrote:﻿
I know you haven't yet cleared all of the bugs, but I tried the azad_72fe13cb test version, and although the output was a bit glitchy (some items showed prices twice), with a little manual cleanup of the output it did the job. Thanks!

**Comment by philipmulcahy** [comment] 2024-10-03 06:51
Sent from my phoneOn 2 Oct 2024, at 22:43, kms54321 ***@***.***> wrote:﻿
I know you haven't yet cleared all of the bugs, but I tried the azad_72fe13cb test version, and although the output was a bit glitchy (some items showed prices twice), with a little manual cleanup of the output it did the job. Thanks!

**Comment by philipmulcahy** [comment] 2024-10-03 21:54
Here is the promised test build: [azad_683c89f5.zip](https://mulcahyfamily.org/azad/azad_683c89f5.zip)

Q: What does it do for me?
A: On top of the previous build (72fe13cb, which got most titles and item descriptions back) It restores item and shipment info. Some shipment status data may be more comprehensive than before, but it's still only for relatively recent orders.

Q: Great! What's the bad news?
A:  shipment.transaction column looks empty. I've not even started to search for where  the data has been moved to - if it's even available at all.

Q: OK - what do I need to do?
A: [Test](https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-try-out-an-experimental-version) it (please), and report back here.

Q: What happens then?
A: I cut a production release, which may then take a few days to run the Google Chrome Webstore gauntlet. In fact I may jump the gun, because this whole "Amazon changed the schema" is probably hurting almost all active users, even if they're not complaining, but I'm still interested in your feedback on 683c89f5.

**Comment by mischumerritt** [comment] 2024-10-04 01:27
Hi,
New to this...looking for data to do some household budgeting analyses.  My reports are showing gaps as noted above.  I'm inclined to wait for the update to propagate, but if you still need a test build exercised for a US customer, I'll check back here and try to jump through those hoops if you need me to.

...I am very impressed.  Thanks for offering real value and support of your charity...in a rational and congenial forum.  Gives me hope for the species!  I've pitched in.
Best regards,
Michael Merritt

**Comment by master-nevi** [comment] 2024-10-04 04:15
> Here is the promised test build: [azad_683c89f5.zip](https://mulcahyfamily.org/azad/azad_683c89f5.zip)
> 
> Q: What does it do for me? A: On top of the previous build ([72fe13c](https://github.com/philipmulcahy/azad/commit/72fe13cb903ea33eb078b21a27a7e3847fcd3562), which got most titles and item descriptions back) It restores item and shipment info. Some shipment status data may be more comprehensive than before, but it's still only for relatively recent orders.
> 
> Q: Great! What's the bad news? A: shipment.transaction column looks empty. I've not even started to search for where the data has been moved to - if it's even available at all.
> 
> Q: OK - what do I need to do? A: [Test](https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-try-out-an-experimental-version) it (please), and report back here.
> 
> Q: What happens then? A: I cut a production release, which may then take a few days to run the Google Chrome Webstore gauntlet. In fact I may jump the gun, because this whole "Amazon changed the schema" is probably hurting almost all active users, even if they're not complaining, but I'm still interested in your feedback on [683c89f](https://github.com/philipmulcahy/azad/commit/683c89f5a0cef75764185f027aefbf77e8317c73).

@philipmulcahy Are there instructions somewhere for how to install these test builds?

**Comment by mischumerritt** [comment] 2024-10-04 12:27
Update: Inevitably, the requested data arrived in a zip file from Amazon today.  It includes the missing items for Kindle unlimited and streaming services.  Reach out if my sharing that detail would help.

...no regrets for my time and monetary support, even if Amazon came through.  Grass roots communities like this are important.  It reminds me of the (historically ironic) 1984 ad.  https://en.wikipedia.org/wiki/1984_(advertisement)  We must rage...constructively...against the machine!

**Comment by ballle98** [comment] 2024-10-04 14:07
tested dev build https://github.com/philipmulcahy/azad/commit/683c89f5a0cef75764185f027aefbf77e8317c73 still not seeing any digital orders

**Comment by philipmulcahy** [comment] 2024-10-04 14:10
@ballle98 please share screenshots and a console log (after clearing cache) because the only examples I've seen so far show the existence of all digital orders, but in some cases does not then give more detail beyond date and order id.

**Comment by philipmulcahy** [comment] 2024-10-04 14:46
I've submitted 1.14.2 to the webstore for review. In recent times, it takes about 24hrs for new versions to be distributed. You can check what version you have in chrome://extensions.

Given such a big change by Amazon, it's to be expected that we're going to be playing whackamole for a bit to nail down residual breaks, but at least on my account (save for transactions) it's doing a good job.

@ballle98 I assume you've seen https://github.com/philipmulcahy/azad/issues/293#issuecomment-2388334269 - for digital orders such as these, the bigger problem appears to lie on the Amazon side of the fence. If they don't fix it, I might be able to reinstate some basic details from the order list page, but that strategy caused a tonne of pain in the past (which is why azad leans so heavily on the order detail pages instead these days).

**Comment by mischumerritt** [comment] 2024-10-04 14:53
Thanks for the update!

Michael
Sent from my iPhone

On Oct 4, 2024, at 10:47 AM, Philip Mulcahy ***@***.***> wrote:

﻿

I've submitted 1.14.2 to the webstore for review. In recent times, it takes about 24hrs for new versions to be distributed. You can check what version you have in chrome://extensions.

Given such a big change by Amazon, it's to be expected that we're going to be playing whackamole for a bit to nail down residual breaks, but at least on my account (save for transactions) it's doing a good job.

@ballle98<https://github.com/ballle98> I assume you've seen #293 (comment)<https://github.com/philipmulcahy/azad/issues/293#issuecomment-2388334269> - for digital orders such as these, the bigger problem appears to lie on the Amazon side of the fence. If they don't fix it, I might be able to reinstate some basic details from the order list page, but that strategy caused a tonne of pain in the past (which is why azad leans so heavily on the order detail pages instead these days).

**Comment by kms54321** [comment] 2024-10-04 17:14
I only need a list of items ordered (digital orders aren't important for me), and version 683c89f5 seems to do that job perfectly. I'll swap it for the published version 1.14.2 when that becomes available, but for now I'm good.

Thanks!

**Comment by philipmulcahy** [comment] 2024-10-05 19:12
I am “at sea”, so can’t check with my laptop, but the developer dashboard claims 1.14.2 cleared review and is available to users. You can expedite update on your browser by visiting chrome://extensions and looking for a button that says something like “update”. It’ll happen on its own eventually but if you are broken and want to use the new one without going through the hassle of installing a test build (thanks to those who did!), then chrome://extensions is your friend.

I intend to close it this ticket real soon now: the transactions problem is captured in a newer (open) one.

**Closed** 2024-10-05 21:41 UTC
Labels: bug, ready_to_release, accepted

**Comment by mischumerritt** [comment] 2024-10-06 01:46
Hi,
Not sure whether to document it here or...not sure.  I realized last night I didn't collect the categories.  I tried today, and 2024 was fine, but the fields were blank in 2023.  I cleared the cache...and they were populated.
Michael
