### ISSUE TITLE
Error caused by too many redirects means no "Save to CSV" button

### ISSUE THREAD

**Issue by ivucica** [philipmulcahy/azad#148] opened 2021-01-15 16:19 UTC
I have an Audible order back in 2015, where Amazon seems to redirect to Audible.com for order information. This confuses the extension, resulting in an error. I am ok with missing some data (the data table shows some information as 'pending' which I am happy to ignore), 

However, right now I can't see the UI for saving the CSV.

**Comment by ivucica** [comment] 2021-01-15 16:22
Strangely, I was missing the UI for 2016 and 2017. It appeared for 2018, but disappeared once the download was complete with 2 errors.

**Comment by philipmulcahy** [comment] 2021-01-16 23:31
I am assuming this is actually a duplicate of #145  - please join in the fun there: I will close this one.

**Closed by philipmulcahy** 2021-01-16 23:31 UTC
