### ISSUE TITLE
Only 1,2,3 month order download buttons are showing up

### ISSUE THREAD

**Issue by NathanChristie** [philipmulcahy/azad#236] opened 2023-09-07 15:48 UTC
**NOTE FROM PHILIP**

> High confidence fix (1.9.32) in review for publishing through Chrome Webstore. If you cannot wait, try out the private build here: https://github.com/philipmulcahy/azad/issues/236#issuecomment-1712777185

**END OF NOTE**

I've purchased the premium version, forced logout, and cleared cache. The extension menu still only shows options for 1m, 2m, 3m. No year options ever are displayed.

![AzodBug01](https://github.com/philipmulcahy/azad/assets/856545/9fcbe6db-9cf9-4dd9-b5f5-e306eb36e131)

**Comment by philipmulcahy** [comment] 2023-09-07 16:29
Let me contrive a quick checklist for you to triage this:
You can stop the checklist if/when you cannot answer yes, because that’ll be a/the cause.

1) Do you have a solitary amazon tab open that shows some orders - something like https://www.amazon.co.uk/gp/css/order-history?ref_=nav_AccountFlyout_orders (replace with your country’s equivalent domain such as amazon.com <http://amazon.com/>) ?
2) Have you refreshed the amazon page since checking you’ve got 1.9.31 installed (see chrome://extensions ) ?
3) Back on the orders page, is there a pull down menu that allows you to choose a year (instead of last three months etc.)?
4) Open chrome developer tools and get sight of the console (a debug logging display that also allows you to type js interactively)
5) Refresh the page again
6) do you see a line that looks like this "advertising years (20) [2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]” attributed to a file called “inject.bundle.js” ?

Up to and including step 3, if you cannot say yes, you’re on your own with Amazon - the extension can not do its thing.
Beyond that, we need to do some more debugging together - let me know when you’re ready :)

Philip

**Comment by NathanChristie** [comment] 2023-09-07 19:05
1) yes, copy / pasted: https://www.amazon.com/gp/css/order-history?ref_=nav_AccountFlyout_orders , which defaults Amazon's order dropdown to "past 3 months" 
2) yes, I've refreshed and launched a new completely new instance of Chrome (v 116.0.5845.179), with the only active Extension as Azad (v 1.9.31).
3) yes, selecting 2023 from that dropdown changes the url to:
https://www.amazon.com/your-orders/orders?timeFilter=year-2023&ref_=ppx_yo2ov_dt_b_filter_all_y2023
and displays my 288 orders across multiple pages. When clicking on the extension icon after selecting the current year, only the 1,2,3m options are displayed.
456) the advertising years array is empty. It seems the getYears() call isn't returning anything for some reason
![AzodBug01a](https://github.com/philipmulcahy/azad/assets/856545/4bfab278-56aa-4e66-9aff-f28a90864c6c)

**Comment by philipmulcahy** [comment] 2023-09-07 21:46
Thanks for digging so deep!
I just logged into my amazon.com account which has exactly one order (I am in the UK), on a hunch and I was able to reproduce the behaviour of only seeing only the 1,2,3 buttons.
I then (on a whim) clicked on "clear cache", reloaded the amazon page and the years appeared.
Hypothesis
1) In a recent commit, I changed the format of of the cache entries to be more space efficient so that more orders can fit in the space allocated by Chrome.
2) To stop this causing problems with old cache entries poisoning new versions of the extension, I implemented a "on-install" event handler that is supposed to clear the cache.
3) That handler is not reliable :( and I didn't get around to fixing it - the solution is relatively simple in concept, but fiddly to implement.
4) In my repro, I think that the old cached messages are preventing the extension from getting the year list from amazon - it thinks it already has that query in cache and falls over when the cache entry is unparseable.

I suggest trying out the cache clear button WHILE YOU'VE got a tab open in the relevant amazon site, then reloading the page, then retrying the popup.

If this works, it's gonna be annoying for a bunch of people for a while but is a reasonable workaround until I can get the cache clearance bug sorted out.

If it doesn't work, we'll have to dig a bit deeper into using the debugger (well done for getting so far with it today!).
For your entertainment, the inject.bundle.js messages you've captured are consistent with the above hypothesis. The error messages are nothing to do with azad - they're amazon code that is co-mingled, and unlikely to be relevant to us.
If it is the cache clearance problem, I am sorry for equipping you with such an annoying foot gun, but I'd rather know that's the issue than be in the dark for longer!

**Comment by NathanChristie** [comment] 2023-09-08 16:12
Thanks for the debugging praise - I'm a former software developer / tester stay-at-home-dadding the last 10 years basically, so it's refreshing to use my brain for something other than dishes. I've attempted your suggestion at hitting "clear cache" while there's a single amazon tab open (logged in and on order page). Still only 1,2,3 options are displayed.

My TypeScript / XPath skills are lacking, and my debugger skills are mostly from Java, so this is as far as I'm able to trace the issue. In inject.ts:getYears() the snapshot constant isn't getting assigned properly for some reason. The closest thing to a clue is an exception in the object's stringValue:

> [Exception: TypeError: Failed to read the 'stringValue' property from 'XPathResult': The result type is not a string. at XPathResult.invokeGetter (<anonymous>:3:28) at Module.findMultipleNodeValues (chrome-extension://mgkilgclilajckgnedgjgnfdokkgnibi/inject.bundle.js:189510:24) at chrome-extension://mgkilgclilajckgnedgjgnfdokkgnibi/inject.bundle.js:208904:65 at async advertisePeriods (chrome-extension://mgkilgclilajckgnedgjgnfdokkgnibi/inject.bundle.js:208992:19)]

Possibly some logging or exception handling if a snapshot.length of 0 is observed would be warranted, as the program can't really continue properly in that case.

**Comment by NathanChristie** [comment] 2023-09-08 17:09
Within the getYears() call's **snapshot** assignment, there's an attempt to retrieve node values from "orderFilter". In examining the page source, which I see is used inside getYears() as **doc**, I can only find a "timeFilter" section node, which contains the years that are subsequently parsed.

**Comment by philipmulcahy** [comment] 2023-09-08 19:55
OK - I think a pincer movement is viable:

1) send me the html from the page azad scrapes to get the year list, I can then play around with xpath on it, and eventually build a unit test case. Here's the url (I think you're using amazon.com right?
https://amazon.com//gp/css/order-history?ie=UTF8&ref_=nav_youraccount_orders
I'm looking for the single html file, not all the other images etc. I suggest you email it as an attachment to azadextension@gmail.com so that the internet cannot see it - it may include some low-grade PII.


2) get you going on debugging - you've got the "good" data to play with...
We are fortunate that the current deployed build has a source map...

Check out this marked-up screenshot that should help you find out more:
<img width="1494" alt="Screenshot 2023-09-08 at 20 36 21" src="https://github.com/philipmulcahy/azad/assets/1668892/2a4213ea-d018-4173-977d-a41508677313">

The scene you see was captured after I
1) opened the debugger on an amazon page that's logged in to amazon.
2) did the marked up stuff (see the arrows for direction of flow)
3) refreshed the page, causing the injected script to run, stopping at the placed breakpoint

The breakpoint location is somewhat arbitrary. There are buttons for stepping through the code on the high right of the debugger.
You'll find that stepping through asynchronous boundaries (such as await, and then) doesn't always do what you expect: the seperated code is actually a sugary representation of a call-back function. Because there's only one thread of this function running at once, you can cope with this by just adding more breakpoints through the func and then just pressing the play button to step to the next break point.
The easiest way to inspect variable values is to point at them, but you can also type them into the console or there's an inspector/watch pane on the right. If you're really skilful, you can put breakpoints in the middle of a line. I tend just to edit the code to put more line breaks in if it's getting that confusing.

Another weapon in our arsenal include me sending you successive test builds, and you sending me back log extracts, but I think the above two paths are going to be faster for both us.

Yours,

Philip

**Comment by philipmulcahy** [comment] 2023-09-08 22:17
Here's a third pincer/debugging-channel, and _maybe_ useful workaround to impacted users...
It involves a local/private build of 1.9.30 (the most recent version before the current 1.9.31).

How to use: 
* download https://www.mulcahyfamily.org/azad/azad_4e24eab1.zip
* unzip it
* Open chrome://extensions enable developer mode
* "load unpacked extension"
* point at the unzipped folder (it'll be called build)
* disable the chrome webstore version
* open an amazon page or refresh an existing one
* use the extension's popup UI to clear the cache
* reload the page
* see if years appear
* let us know here whether it worked for you, and what amazon site you're using (which country)

Some considerations:
* Remember to disable/uninstall it before turning the webstore one back on again.
* It won't update
* Having more than one running at the same time won't damage your system or chrome, but they're probably not going to do a great job of fetching your amazon data! (but if you're here, looking at this bug, then you may not care that much, but once we've fixed this bug you _will_ care!)

**Comment by shoodes** [comment] 2023-09-08 22:43
Hey,

I tried the steps stated above and I still don't have the years showing up on the extension. I am using Amazon US (Amazon.com) with Chrome v116.0.5845.180 with the developer extension you sent in the post.

**Comment by philipmulcahy** [comment] 2023-09-09 00:21
I am beginning to wonder if Amazon has changed something for some users/sites. Getting me the html from the link I shared is the way forward if that is the case. I am stuck at home oncall on Sunday, so if it is a quiet day I can work on a fix.Sent from my phoneOn 8 Sep 2023, at 23:44, shoodes ***@***.***> wrote:﻿
Hey,
I tried the steps stated above and I still don't have the years showing up on the extension. I am using Amazon US (Amazon.com) with Chrome v116.0.5845.180 with the developer extension you sent in the post.

**Comment by shoodes** [comment] 2023-09-09 00:27
I sent an email with the html file I pulled from the "Your Orders" Page.

**Comment by NathanChristie** [comment] 2023-09-09 00:52
> 

Tried these steps twice and still only see 123 months. I edited line 208281 of the inject.bundle.js to search on "timeFilter" instead of "orderFilter" and it's working. The years are all showing now.

**Comment by philipmulcahy** [comment] 2023-09-09 05:24
Nice work Nathan!I will sort out a version that works for both alternatives this weekend and get it into review with the chrome web store.Sent from my phoneOn 9 Sep 2023, at 01:52, NathanChristie ***@***.***> wrote:﻿


Tried these steps twice and still only see 123 months. I edited line 208281 of the inject.bundle.js to search on "timeFilter" instead of "orderFilter" and it's working. The years are all showing now.

**Comment by philipmulcahy** [comment] 2023-09-09 14:58
I have html from @shoodes and @NathanChristie thank you both!

1) it looks like it's an Amazon change that has broken us, not a bug from me (though there are many!)
2) it looks like Amazon are making improvements, not trying to break us on purpose.
3) I don't expect problems getting things working in the next day or so, and I am incentivised to do so - presumably Amazon are rolling this change out progressively, so the longer I leave it the more annoyed users there'll be.

**Comment by philipmulcahy** [comment] 2023-09-09 23:05
59417b471 (in a branch called no_years) has a new unit test that runs the getYears code against html from @NathanChristie (.com), @shoodes (.com?) and @philipmulcahy (.co.uk).

 {
    test_id: 'GET_YEAR_NUMBERS_./src/tests/azad_test_data/get_years/NathanChristie_2023-09-08.html',
    passed: false,
    defects: []
  },
  {
    test_id: 'GET_YEAR_NUMBERS_./src/tests/azad_test_data/get_years/PhilipMulcahy_2023-09-09.html',
    passed: true,
    defects: []
  },
  {
    test_id: 'GET_YEAR_NUMBERS_./src/tests/azad_test_data/get_years/shood_2023-09-08.html',
    passed: false,
    defects: []
  }
so _all_ I need to do now is fix getYears...

**Comment by philipmulcahy** [comment] 2023-09-09 23:45
How does https://www.mulcahyfamily.org/azad/azad_f758f0b0.zip look?
Since at least .co.uk is still using the old identifier, I've gone with 
```'//select[@name="orderFilter" or @name="timeFilter"]/option[@value]'```
which passes the new test with all three html samples.
If either of @NathanChristie or @shoodes reports success with the above build, I'll wrap up 1.9.32 tomorrow, send it for review and rapid rollout.

**Comment by philipmulcahy** [comment] 2023-09-10 10:05
NO NO NO!
I suspect that f4758f0b0 is not good: I copied getYears's code to a place that'd be easier to unit test, but (we will see shortly) left the old, broken code in place, and I fear that the old code is still wired in (except for the tests).
Don't bother testing until I share a new version.

**Comment by philipmulcahy** [comment] 2023-09-10 10:32
fixed: https://www.mulcahyfamily.org/azad/azad_c03dfe35.zip

**Comment by axjasf** [comment] 2023-09-11 23:25
> fixed: https://www.mulcahyfamily.org/azad/azad_c03dfe35.zip

I can confirm the original issue and this version corrected it (Amazon.com).

**Comment by philipmulcahy** [comment] 2023-09-12 12:45
Fixed in 1.9.32; pushed 25% on 2023-09-110; pushed 100% on 2023-09-12.
I will close this bug as soon as the 100% push is approved by google.

**Comment by philipmulcahy** [comment] 2023-09-12 13:54
push complete

**Closed by philipmulcahy** 2023-09-12 13:54 UTC
Labels: bug, accepted
