### ISSUE TITLE
Extracting payments from multi-delivery orders

### ISSUE THREAD

**Issue by JonSilver** [philipmulcahy/azad#7] opened 2017-10-18 11:10 UTC
We frequently have to reconcile Amazon orders with bank payments. Since Amazon only charges your payment card on despatch, each delivery in an order represents a separate bank transaction, making the order total useless for reconciliation purposes.

The individual charges for an order are available using the following url pattern:
`https://www.amazon.<ext>/gp/css/summary/print.html/ref=oh_aui_ajax_pi?ie=UTF8&orderID=<orderId>
`

The following selector path extracts the individual charges from the table at the end of the document:
`body > table:nth-last-of-type(2) > tbody > tr > td > table:last-child > tbody > tr > td > table > tbody > tr:last-of-type > td > table > tbody > tr > td:nth-child(2) > table > tbody > tr`

Although it would slow down the extraction process, it would be incredibly useful to have the extension optionally perform these queries and include multiple lines in the query results for each order where there are several deliveries/charges.

**Comment by philipmulcahy** [comment] 2017-10-21 22:15
@JonSilver 

731b551058b21eee72cf9ceb070957229ef281fb (just pushed now) can display credit card transactions but only for non-digital orders.

Questions for you:
1) If you have any non credit card payments, can you give me the html source for an example payment page (per your url)? This is so I can craft suitable xpath queries. Even if you've redacted sensitive info, I suggest sending it to me privately, in case you've missed anything.
2) Do you know an equivalent url pattern for digital orders?

Thanks,

Philip

**Comment by JonSilver** [comment] 2017-10-22 15:39
Thanks, @philipmulcahy I'll go and have a look.

I have no non payment card payments, alas.

Digital orders seem to use a different page:
    `https://www.amazon.<ext>/gp/digital/your-account/order-summary.html/ref=oh_aui_dor_o00_?ie=UTF8&orderID=<orderId>`

**Comment by philipmulcahy** [comment] 2017-10-22 21:42
OK - I can probably figure out how to get the values out. I'd found one of them, but wasn't sure if it was consistently available.
I have got a busy week or so, so it might be a few days.
In the mean time, do you know if it's possible to have digital items in the same order as normal items? I don't have any examples in my history...

**Comment by philipmulcahy** [comment] 2017-10-22 21:51
Unless someone says different, I'll assume that orders starting with D use the /gp/digital/your-account/order-summary.html/ref=oh_aui_ URLs for payment info.

**Comment by philipmulcahy** [comment] 2017-10-25 22:24
Bad news - the card info on digital orders is loaded by a script - it's not in the page as downloaded - that means we're into the territory of byzantine recreation of the in-browser page rendering process. I can get the amount, but we already have that from the main page. It's the same story for both versions of the digital URLs.

**Comment by philipmulcahy** [comment] 2017-10-25 23:24
https://github.com/philipmulcahy/azad/commit/4932db0ebfd089fe911b5ab2f394634cb5c98c9e
@JonSilver do you know how to run this before I push it out on the web store? If not, it's dead simple...
```
git clone https://github.com/philipmulcahy/azad.git
visit chrome://extensions, disable the public version of the extension
click on "load unpacked extension"
point it to where you cloned the repo to.
```

**Comment by JonSilver** [comment] 2017-10-26 06:25
Yup, I’ll give it a try today and report back. Thanks for all your work on this.

Shame about the digital orders - I guess it was done at a different time in a different way by different developers. I’ll keep on searching for alternatives. I’m amazed there’s no Amazon customer API, but beggars can’t be choosers, alas.

**Comment by JonSilver** [comment] 2017-10-26 10:46
Tried it, @philipmulcahy - and it works well. Thank you for making the effort, it's made the whole thing more useful.

One small problem - the table extends slightly over the right hand edge of the viewport on my PC with Chrome@latest. I fixed it locally with a F12/devtools CSS kludge.

**Comment by philipmulcahy** [comment] 2017-11-01 23:41
I can't reproduce the overspill on a windows 10 VM (I mostly develop on Mac OS).  I've never looked at how the jquery datatable styling works before. Is it possible you have another content script or user stylesheet?

**Comment by JonSilver** [comment] 2017-11-02 07:32
It’s possibly a local effect - I’ll dig deeper and see if I can find the cause.

**Comment by philipmulcahy** [comment] 2017-11-02 22:59
Closing this as the payments is sorted - I'll push out on web store soonish.
@JonSilver please feel to continue the overspill issue in a new ticket when you're done investigating.

**Closed** 2017-11-02 23:10 UTC
