### ISSUE TITLE
CSV download/blue button missing, even on 1.8.15 and non-2017 years

### ISSUE THREAD

**Issue by JasperRobinson** [philipmulcahy/azad#35] opened 2018-09-07 12:39 UTC
Hi, 

I've a horrible feeling that I might be doing something blond, but like tmkaplan I don't see the CSV blue button. Selecting a year's orange tab throws your extension into action but I can't get to the output. I've used your extension several times, successfully, most recently about 18 mo ago. 

I don't know if it's significant but the Amazon Order History Reporter button on the top right looks like it's not on/operational. In the Extensions, Amazon Order History Reporter is on. I'm using 1.8.15, which I think was the fix for tmkaplan.

![image](https://user-images.githubusercontent.com/8968646/45219331-6e504300-b2a2-11e8-8c8e-83bf4ba73618.png)

I've tried turning Amazon Order History Reporter on/off (IT Crowd tip) and reinstalling; neither changed my symptoms. 

If you've any tips, I'd love to hear them - I don't fancy doing this manually!
Thanks, Jasper

**Comment by Iruwen** [comment] 2018-09-07 13:02
> I've a horrible feeling that I might be doing something blond

Then we both are, because I just came here for the same reason.

**Comment by philipmulcahy** [comment] 2018-09-07 20:51
This might be good news (for me, and hopefully eventually for you)...
1.8.15 wasn't meant to be a fix - Toby's logs were not conclusive, so I added an extra bit of debugging code.
In order for this to pay off, and (maybe) allow me to figure things out and fix them, I'm going to need a little help from you folks:
1) Reproduce the problem as per your screenshot
2) Wait for the orange stuff in the top right corner to stop
3) Download the whole console log and attach it to this ticket:
    i) Chrome developer console (three dot icon/button on right hand side|More tools|Developer Tools)
    ii) Click on "Console" pane (in a bar near the bottom, normally)
    iii) Press the orange year button you want to fetch
    iv) Watch the console fill up with logs, and wait for stuff to stop happening in the orange counters on the top right hand side.
    v) Right click somewhere in the console logs | Save as... (choose a file name)
    vi) rename the file by adding .txt to the end (so github will allow it)
    vii) Drag the file to an open comment box in this ticket.
Here's hoping...
Thanks,
Philip

**Comment by JasperRobinson** [comment] 2018-09-08 08:18
No, thank you, Philip!

I've attached the console output from 2009. I checked 2017 too - the trip up seemed to happen at the same place (js 495).

Cheers, Jasper

[Amazon2009.txt](https://github.com/philipmulcahy/azad/files/2363146/Amazon2009.txt)

**Comment by philipmulcahy** [comment] 2018-09-08 21:48
Gah! this isn't the same as Toby's issue - it's _caused_ by a typo in the debugging code which I clearly failed to test properly. 1.8.16 is propagating right this minute with a fix. Sorry for the annoyance. (Should be with you tonight).
Philip

**Comment by philipmulcahy** [comment] 2018-09-10 21:30
closing: no further complaints

**Closed by philipmulcahy** 2018-09-10 21:30 UTC
