### ISSUE TITLE
Scrape won't complete

### ISSUE THREAD

**Issue by elusis** [philipmulcahy/azad#134] opened 2020-11-04 02:56 UTC
I've run AZAD several times on my order page but at some point it seems to hang and never complete. I get a spreadsheet-looking output in my browser window, but I don't actually get a downloadable result. It worked for me last month.

https://smile.amazon.com/gp/css/order-history?ref_=nav_orders_first

<img width="312" alt="Screen Shot 2020-11-03 at 6 55 37 PM" src="https://user-images.githubusercontent.com/30632059/98064020-30a9bf00-1e06-11eb-8657-f148afc38cec.png">

I pulled the debug file per your instructions in the README but they save as a .json file in Chrome for Mac, which Github doesn't seem to like as an attachment? I saved it as a .txt file anyway.  

It looks like logging isn't enabled by default so I don't have a

 log to attach.

**Comment by philipmulcahy** [comment] 2020-11-04 11:17
The log is what we need here: debug dumps only cover single orders that have “completed” and are mostly useful for explaining/fixing partial or bad data.
When you say the console log is disabled, have you managed to open the dev tools in chrome?

Yours,

Philip

**Comment by elusis** [comment] 2020-11-04 16:45
Yes, I know how to open the Dev tools.  What would you like from there?  I
looked but there's not a log tab.

**Comment by philipmulcahy** [comment] 2020-11-04 20:08
Esc key might make it appear

Yours,

Philip

**Comment by elusis** [comment] 2020-11-04 20:28
Here's a screen shot of what I have under the Console tab - is this what
you're looking for?

**Comment by philipmulcahy** [comment] 2020-11-05 21:24
I see no screenshot, but no need to try again - what I need is the log file...
...take a look at these screen shots. Windows is similar, but getting the dev tools up is a different menu item or key combination:

<img width="1440" alt="Screenshot 2020-11-05 at 21 17 40" src="https://user-images.githubusercontent.com/1668892/98297813-ea429480-1fac-11eb-98bd-e0b14c16d55f.png">
<img width="1440" alt="Screenshot 2020-11-05 at 21 17 21" src="https://user-images.githubusercontent.com/1668892/98297818-ed3d8500-1fac-11eb-8a61-a38188cbb5e3.png">
<img width="838" alt="Screenshot 2020-11-05 at 21 20 39" src="https://user-images.githubusercontent.com/1668892/98297840-f4fd2980-1fac-11eb-8098-d3bae6abc849.png">

**Comment by elusis** [comment] 2020-11-06 01:22
Yeah, that's what I sent you a screenshot of.  Attached another one now.

Save as did work however, see attached.

**Comment by philipmulcahy** [comment] 2020-11-07 01:18
I see no log attached: can you see it on GitHub? (as opposed to on your email, if that is how you sent it). You can send it to the project gmail address as well, but let me know here too so I can look out for it. Sorry if I am being dense.
You might want to remove that json file attachment in your earlier post: I haven’t looked but it might contain PII and this thread is visible to anyone.

**Comment by elusis** [comment] 2020-11-07 01:25
I sent it via email, both times.

**Comment by philipmulcahy** [comment] 2020-11-07 01:32
Look at GitHub...

**Comment by elusis** [comment] 2020-11-07 03:03
I assumed getting notifications in email meant I could send attachments there. Apologies. 
[smile.amazon.com-1604625640071.log](https://github.com/philipmulcahy/azad/files/5504215/smile.amazon.com-1604625640071.log)

**Comment by philipmulcahy** [comment] 2020-11-07 16:37
The log seems to suggest that the extension is failing its saved settings from Chrome storage. You can probably get around this by opening the popup, and then selecting one or more of the checkboxes (make sure you change one of them) then closing and reopening - the change should have persisted (you can put them back the way you want them at this stage).
This should be a one-time thing.
Then try pressing a year scrape button and let me know how you get on.

Not caused by azad, but if it were my account, I'd want to know what "h1-vendors-main-popover-wallet.js:149 WebSocket connection to 'ws://localhost:8000/socketcluster/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
o @ h1-vendors-main-popover-wallet.js:149" is (also in your log).  Something is trying to talk to an open socket on your machine. Unless you've deliberately installed software as well as a matching chrome extension, this is bit suspicious...

Yours,

Philip

**Comment by ScottMcNay** [comment] 2020-11-08 14:15
Google search suggests that "h1-vendors-main-popover-wallet.js" might be an
Etsy thing.

--Scott.

**Comment by elusis** [comment] 2020-11-12 03:16
Latest results after doing as suggested.

I don't have any sort of Etsy extension loaded that I'm aware of.  :-/
 
[smile.amazon.com-1605150949217.log](https://github.com/philipmulcahy/azad/files/5528035/smile.amazon.com-1605150949217.log)

**Comment by ScottMcNay** [comment] 2020-11-12 07:35
It's apparently not an Etsy extension, it's an Etsy web page. Might be
software used by Etsy, not necessarily the Etsy site itself.

--Scott.

**Comment by Abba-** [comment] 2020-11-12 20:45
I'm having very similar issues.
Checking a box doesn't seem to save.
Randomly while scraping I get a new window (which I think is trying to do the Amazon login) but is just a ERR_FILE_NOT_FOUND.
I do eventually get a HTML table, but when I click get CSV, the buttons on top just disappear and leave me with just the HTML table.

**Comment by philipmulcahy** [comment] 2020-11-13 07:22
Attaching a console log file (you need to log into GitHub and drag it onto a post: email won’t work) is what you need to do here.

Yours,

Philip

**Comment by philipmulcahy** [comment] 2020-11-16 22:39
@elusis the lines containing "net::ERR_TOO_MANY_REDIRECTS" will have been accompanied by multiple popup rows on your screen - they disappear after a few seconds unless you move your mouse pointer over them, because if you had to click to ack them, you'd need to do a lot of clicking. They tell you to log out and log back in again - there's a button on the control window to do the logout comprehensively and quickly - you have to log yourself back in. In your case it looks like the digital orders bit of Amazon has got bored of you first.

**Comment by philipmulcahy** [comment] 2020-11-30 15:27
I am assuming this is resolved, but don't be shy about re-opening!

**Comment by elusis** [comment] 2020-12-06 19:59
Hi, re-opening because it's a new month and I needed to scrape again.

Scrape completed this time I think? I cleared the cache first. But when I clicked to download the .csv file, instead it just went to a new page with a table displayed as text.  I was able to select all, then paste into an Excel spreadsheet, but there were formatting issues (hidden "merged cells" that were not "the same size") that interfered with sorting by date, because the results were not in date order.

(hope this screen shot does not post as too huge)

<img width="800" alt="Screen Shot 2020-12-06 at 11 41 26 AM" src="https://user-images.githubusercontent.com/30632059/101290944-14f55800-37ba-11eb-8a0a-1e9401a35dd8.png">

**Comment by elusis** [comment] 2020-12-06 20:03
Oh, and the results of my copy/paste/sort is missing a bunch of items that I can see just scanning my orders page. I've got text wrapped, but it's showing only one item per date.

**Comment by elusis** [comment] 2020-12-06 21:45
I'm also concerned that after running the scrape today, and using the "clear cache" (but not "log me out) button, I'm now being told by Amazon that there's been a request put on my account to change my password because the note says "provided Amazon information to an external link" - as if I clicked on a phishing email, then realized it and called them asking them to disable my old password. Which I did not (click on an email, or ask them to make the re-set). The only interaction with Amazon I've had today is running the scrape tool and clicking "clear cache." I'm on hold with them while they're trying to figure this out but wanted to document this as it may be related.

**Comment by philipmulcahy** [comment] 2020-12-07 08:50
I think another console log is what we're looking for here: You should be able to see the csv button at the top when the scrape has finished and I don't see it in your screenshot (which worked and is useful).
Copying and pasting html pages into excel is not a winning strategy - problems such as you describe are common.
As mentioned above, the csv button is what you need, or as an ugly workaround using another chrome extension such as "Table Capture" (not mine, but really good).

On security, I don't think there's a way that azad could have triggered your password change conversation, unless Amazon have decided they don't want anyone using the extension (which is plausible - it's clear they don't want people having easy access to their own data). If they were clever enough they could work out that because you are fetching stuff so fast, it cannot be a person clicking all those order links. I had a small panic that you'd sent me html and I'd looked at it in my browser to help debug your issue, but reviewing this ticket suggests that you didn't and I have not. If that were the route, it would be both good (for amazon customer security/protection) and terrible - A because it'll make it a fair bit harder to debug some issues and B because it's taken them weeks to react, but again, I don't think it's what's happened.

**Comment by Abba-** [comment] 2020-12-07 17:01
Can confirm still have issue, seems similar.

1. https://www.amazon.com/gp/css/order-history?ref_=nav_orders_first
1. clear cache
1. 2020
1. table popped up after about 1200, but window had count still going up
1. Then new tab opened with following URL  - I think that is a potential bug trigger chrome-extension://mgkilgclilajckgnedgjgnfdokkgnibi/gp/digital/your-account/order-summary.html/ref=ppx_yo_dt_b_dpi_o09?ie=UTF8&orderID=D01-0123456-1234567&print=1
1. --> The page displayed ERR_FILE_NOT_FOUND - obviously because that URL makes no sense

1. Saved order debug info for a digital order: Got status:200 while fetching /gp/digital/your-account/order-summary.html/ref=ppx_yo_dt_b_dor_o00?ie=UTF8&orderID=D01-123456-1234567 This might be because you are not fully logged in to Amazon.
1. Clicked download csv
1. button disappeared, just got html table

Files (please let me know when retrieved) https://drive.google.com/drive/folders/1FJozsqRjZzqAdzrJq_My7zp_Nlf_POT-?usp=sharing

**Comment by philipmulcahy** [comment] 2020-12-07 20:25
Hi Abba,

I've downloaded the files and removed the link to google drive by editing your post - please consider using azadextension@gmail for safely transferring confidential data going forward - the entire internet can see this thread...

It might be a few days before I get time to look properly, but I'll get there in the end.

Yours,

Philip

**Comment by philipmulcahy** [comment] 2020-12-19 22:29
I've offered up v1.9.17 to the approval gods - it might be with you tomorrow, but then again it might not... keep your eye open for it.

**Comment by philipmulcahy** [comment] 2020-12-21 22:07
It's been out for 24-36 hours globally - let me know...

**Comment by Abba-** [comment] 2020-12-22 00:42
Sorry, same issue tried several times.
The popup that happens from a digital order is fixed.
But still when clicking 'download csv'  the buttons just disappear.

1) years didnt show, after chrome restart it came up
2) clicking 2020 didnt update passed queue 111 with 11 completed.
3) cleared cache / stop a few times
4) table popped open before popup showed (popup seems to lag - froze at 40 queues, 681 completed, 626 errors (I dont think the error count is accurate)
5) clicking button just made buttons disappear.

**Comment by philipmulcahy** [comment] 2020-12-26 16:20
You are welcome @Abba- . I think that I'm going to need another console log from the current version and a screenshot showing where you've got to when the log finishes - the errors from login failures and trying to open the login page with an incomplete page are hiding the problem you're seeing now.

I just tested the extension on my UK (main) and US (minimal) accounts.
What happens for me after pressing on a year button is:
1) a bit of a pause while it gathers all the order ids (and so knows how many rows the table needs)
2) the table replaces the amazon page
3) the csv and table mode buttons appear on the page at the top, with an orange progress bar
4) I wait until the orange bar has filled its box
5) then I click on the csv button
6) longish pause (annoyingly long, without any sign of the furious activity going on behind the scenes)
7) table reappears in the non-fancy format
8) file appears in downloads folder, with some "toast" activity at the bottom of the window.

**Comment by philipmulcahy** [comment] 2020-12-27 17:23
I've built a test version that has a decent chance of addressing the problem: https://www.mulcahyfamily.org/azad/azad_a313a03b.zip and has extra logging that'll help us figure out what's happening if it doesn't.

to use:
1) download and unzip the above link
2) open chrome://extensions
3) enable developer mode
4) disable the web store version of the extension
5) "load unpacked extension" and point to the unzipped folder
6) try it out
7) send me your feedback
8) remember to disable the experimental version and re-enable the web store one

**Comment by Abba-** [comment] 2020-12-27 18:03
No luck with this version.
Emailing full log, main errors are for digital orders:
HTTP0: too many redirects when fetching https://www.amazon.com/gp/digital/your-account/order-summary.html/ref=ppx_yo_dt_b_dor_o03?ie=UTF8&orderID=D01-xxxxxxxx which has been redirected You might want to consider using the "force full log out" button and logging yourself back into Amazon.

When download csv is clicked the error is JSON.parse blew up with: SyntaxError: Unexpected token u in JSON at position 0 while parsing:undefined

**Comment by philipmulcahy** [comment] 2020-12-27 21:45
@Abba- drat! did you do the logging out thing? Amazon appear to have got less tolerant of "old" logins recently.

**Comment by Abba-** [comment] 2020-12-27 21:57
Just to confirm you mean the ‘force logout button’?

**Comment by philipmulcahy** [comment] 2020-12-27 22:13
Yep - when I made the code changes yesterday (for the test version you have), it detected a bunch of order queries that were failing (that had silently failed previously), and it is now assuming that they _might_ be due to stale login. In my case doing force logout (or just using the amazon logout button - either works) did the trick for me, and I got a clean run in one hit. You don't want to clear the cache between runs unless you're not making progress or you're using a new version of the extension, or Amazon have made changes to their site.

**Comment by Abba-** [comment] 2020-12-28 01:48
Tried it again on fresh chrome profile and it worked.  I cleared some cookies completely and its working on my main chrome profile now :).

Also want to send you some orders that the payment method doesn't come up properly (or other bugs).  What's the best way to collect these sample orders?

**Comment by shesmer** [comment] 2020-12-28 03:27
I have the same issues. Do you want me to try the test version or just wait for a new updated version of yours?

**Comment by philipmulcahy** [comment] 2020-12-28 07:43
@Abba_ Great!
Let’s do bad orders on a different ticket: this one is starting to sprawl. Make a new one but send the order dumps on gmail, referencing order ids in the ticket, one or two should be enough to start. Fair warning: payment info is hard: Amazon keeps moving the goalposts.

Yours,

Philip

**Comment by philipmulcahy** [comment] 2020-12-28 07:47
Stephan: I would try the test version since Abba_ appears happy. If it doesn’t work for you (look out for pop ups about needing to log out + in), then please attach a log.

Yours,

Philip

**Comment by shesmer** [comment] 2020-12-28 16:02
I do have another update. I went into chrome and deleted all cookies under *.amazon.com and retried. It just worked this time. Very strange.

**Comment by shesmer** [comment] 2020-12-28 16:06
This must have been a fluke because I just tried again and I get tons of errors again

**Comment by philipmulcahy** [comment] 2020-12-28 17:36
@shesmer if you're trying to post logs, they're not sticking - you have to do it on a browser - e-mail attachments get stripped off...

**Comment by philipmulcahy** [comment] 2020-12-31 22:29
I'm assuming we're all happy now. v1.9.18 is in review. It has a couple more fixes beyond azad_a313a03b.zip. Normally stuff gets published in about 24 hrs.

**Closed by philipmulcahy** 2020-12-31 22:29 UTC
Labels: bug

**Comment by elusis** [comment] 2021-01-03 01:47
Sorry, it's end of month again so I needed to run another scrape finally.

First effort:

<img width="1494" alt="Screen Shot 2021-01-02 at 5 34 21 PM" src="https://user-images.githubusercontent.com/30632059/103470077-46facb00-4d22-11eb-9c15-7154eb32c86e.png">

Did the forced logout, logged in again, cleared cache. Second effort:

<img width="1487" alt="Screen Shot 2021-01-02 at 5 41 23 PM" src="https://user-images.githubusercontent.com/30632059/103470087-642f9980-4d22-11eb-88b5-bd2aa9e591e4.png">

Never generated a downloadable file. Hung at 595 completed.

I've saved the log; let me know if you'd like it.

**Comment by Abba-** [comment] 2021-01-03 01:51
@elusis Are you sure the extension is updated to 1.9.18? chrome://extensions/?id=mgkilgclilajckgnedgjgnfdokkgnibi  Your display looks like what previous version did on my end.  If yes, maybe try the test version also.

**Comment by elusis** [comment] 2021-01-03 02:09
I didn't see an update - should it auto-update or do I have to do it
manually?

**Comment by Abba-** [comment] 2021-01-03 18:16
I think it does but if if the version is older I think a little arrow appears next to it to force the update on chrome://extensions

**Comment by elusis** [comment] 2021-01-03 19:32
Doesn't show one for me?

**Comment by Abba-** [comment] 2021-01-03 19:33
What version do you see?
