### ISSUE TITLE
Subscribe and Save

### ISSUE THREAD

**Issue by axjasf** [philipmulcahy/azad#237] opened 2023-09-12 20:40 UTC
In the US, for some items, there' a "subscribe and save" offering that comes with a discount. I am not seeing this reflected in the header or item files, that leads to the "total" in header being higher than the payment itself.

**Comment by philipmulcahy** [comment] 2023-09-13 20:26
Table stakes for this one is at least three debug json files for orders displaying this behaviour so that whoever picks it up has a chance at being able to pick through the html, code the feature and add a regression test. You should email them to the project's email address (with this issue's title and number in the subject), and post back here to say you've done it.

**Comment by alfredoagg** [comment] 2024-01-03 16:29
Having same issue here. Has this been addressed?
Thanks for a great product, nonetheless!

**Comment by philipmulcahy** [comment] 2024-02-24 22:17
@alfredoagg see my post above yours - there's no use in people asking for stuff without giving me the toe-holds to address those wishes. I will close this ticket in about a month if no-one provides me what's needed, because there's no point in keeping it open when there's nothing I can do.

**Comment by alfredoagg** [comment] 2024-03-23 07:48
Hi Philip,
I sent the email as requested to the project's email address with this issue's title and number in the subject.
Thank you

**Comment by philipmulcahy** [comment] 2024-04-04 19:38
I've got a json file from @alfredoagg (thanks) with data of his that should be enough for me to take a shot at understanding and fixing this bug, and I've started doing so.

**Comment by philipmulcahy** [comment] 2024-04-07 21:50
I've got something working with the data @alfredoagg shared.
@alfredoagg please test [azad_5e1f8c12.zip](https://www.mulcahyfamily.org/azad/azad_5e1f8c12.zip) (see also [this article on how to test](https://github.com/philipmulcahy/azad?tab=readme-ov-file#how-to-try-out-an-experimental-version)) and let me know how you get on.
If it's good, I'll publish it to the webstore version.

(Non .com/.ca/.co.uk users: this won't help you, because right now only a .com user has shared a relevant order with me - if you want your language/site supported for subscribe and save, then please share a json debug file with me for an appropriate example order from your account.)

**Comment by philipmulcahy** [comment] 2024-04-09 20:29
Gah! I forgot about the item level scrape - I only worked on the order level stuff: back to the editor for me.

**Comment by philipmulcahy** [comment] 2024-04-10 21:50
I've done some more investigation, looking at @alfredoagg's order ending in 5652241.
The S&S discount is not recorded against the item, it's against the whole order.

This presents us with a bit of a problem: do we know if S&S orders with more than one SKU/ASIN are possible? If they are, then @alfredoagg and friends don't get to have all the nice things they would like to have.

If we're very confident that S&S orders can only have exactly one ASIN, then we could copy the order level discount to the item table row, but if not, then I suggest it would not be wise to attempt to distribute the savings across the item rows according to some made-up algorithm.

Postscript #1 
As I write this it occurs that someone is going to suggest: "Philip: why can't you be clever and do the copy when there's only one item row?" I don't know for sure - let me think about it, but it feels a bit hacky, and the first time someone finds an order with two S&S ASINs I will get shanked.

Postscript #2
If the 1:1 condition seems to hold, then the test build should already pull all the data you need - you can simply join your items table to your orders table using your preferred technology (vlookup for sheets, left join for sql, etc.).

**Comment by philipmulcahy** [comment] 2024-04-18 06:53
I think that is WAI: Amazon doesn’t show the discounted item price anywhere does it? AZAD (by design principle) does not do arithmetic anywhere with money numbers except for column sums in the displayed tables (and that feature causes me a nearly unacceptable level of support load already)I am looking at this on my phone right now, so cannot see pictures: if you have provided me a screenshot of an order where the discounted price is shown by Amazon, AND the matching json file, you have my apologies and I will get back in my box and work the problem some more: just point me in the right direction.On 9 Apr 2024, at 21:29, PHILIP MULCAHY ***@***.***> wrote:﻿Gah! I forgot about the item level scrape - I only worked on the order level stuff: back to the editor for me.On 9 Apr 2024, at 13:39, Alfredo Guerra ***@***.***> wrote:Hi Philip,Thank you so much for working on this.I went ahead and tested the beta package. Unfortunately, the "full" (non Subscribe & Save) price still shows up when I download an order report. This is still an issue when I click on the "items" option in the Amazon extension.Interestingly, in the "shipment" option, the correct price shows up (the problem here is that some of us want to be able to see a report with each individual item in a separate row).Let me know if I should send another json file or a screenshot.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by alfredoagg** [comment] 2024-04-19 03:26
Hi Philip,

The discounted price for a subscribe & save item shows up in the Amazon order summary. The picture I attached earlier shows a subtotal price, then subscribe & save discounts, and a net total (so far, the "item" scrape feature scrapes the "subtotal" and not the "grand total" price).

Let me know if this clarifies things.

Thank you,


Alfredo
________________________________

**Comment by philipmulcahy** [comment] 2024-04-21 20:32
Hi @alfredoagg!

If you're referring to The screenshot with filename "Screenshot of Subscribe Save Issue N2.jpg" is for the order, not for the item, so logically no prices are quoted:
![image](https://github.com/philipmulcahy/azad/assets/1668892/38253fd9-1c2a-4990-b17e-cbdbad335bb0)
The number I think you want on the item report (2.49) is associated with the single item in the order, but it's only visible to Azad as an order level aggregate of all of the items in the order (in this case, one item). If there is more than one ASIN in the order, then we could not backtrack.

If I've done what I believe I've done in azad_5e1f8c12.zip, then at the order level, you've got the total (net) amount, and the tax, and the s&s discount amount. From the item level report, you've got the undiscounted price.
If your order is for a single item, you've got everything you need. If it isn't, amazon doesn't offer me a way to reconstruct the allocation of discount to item.

**Comment by alfredoagg** [comment] 2024-05-01 12:02
Hi Philip,

Thank you for your response (and for all the time devoted to this).
I think your approach will work. I double-checked, and all Amazon subscribe and save items appear as separate orders, making them easy to identify in the "orders" scrape option.

I was wondering if using the "orders" price for these items (so that they reflect the discount) be possible as a workaround when doing the "items" scrape. But I guess you would need a way for you to identify which items/orders are "subscribe and save", and I don't know if that is possible. But in any case, if this would be time-consuming, please disregard this comment. As things stand, the orders scrape approach would do the job.

Thanks again!

________________________________

**Comment by philipmulcahy** [comment] 2024-05-31 09:37
if you're seeing this (soon to be closed) ticket and you think you've got a way around the problems we encountered, then please reopen it and let us know!

**Closed by philipmulcahy** 2024-05-31 09:37 UTC
Labels: enhancement

**Comment by philipmulcahy** [comment] 2024-06-10 10:52
a9e492c7e aka v1.13.0 submitted for review and then rollout this morning UK time - expect it to be globally deployed in less than 48hrs - I'm not planning any further updates unless someone re-opens this ticket.
